-- Schema for core-erp
CREATE TABLE Customers (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    Email NVARCHAR(200) NOT NULL,
    Phone NVARCHAR(100) NULL,
    Address NVARCHAR(400) NULL
);

CREATE TABLE Contracts (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Number NVARCHAR(100) NOT NULL,
    CustomerId INT NOT NULL REFERENCES Customers(Id),
    StartDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    EndDate DATETIME2 NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Active'
);

CREATE TABLE Slas (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ContractId INT NOT NULL REFERENCES Contracts(Id),
    Metric NVARCHAR(100) NOT NULL,
    Threshold NVARCHAR(100) NOT NULL
);

CREATE TABLE Assets (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    Type NVARCHAR(100) NOT NULL,
    ContractId INT NOT NULL REFERENCES Contracts(Id)
);

CREATE TABLE Billings (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ContractId INT NOT NULL REFERENCES Contracts(Id),
    Amount DECIMAL(18,2) NOT NULL,
    BillingDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Invoices (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    BillingId INT NOT NULL REFERENCES Billings(Id),
    Number NVARCHAR(100) NOT NULL,
    IssuedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    Paid BIT NOT NULL DEFAULT 0
);
